--- 
before_install:
  - "cd .."
  - "python -m pip install --user virtualenv"
  - "virtualenv venv"
  - "source venv/bin/activate"

install: 
  - "pip install -r requirements.txt"
  - "python manage.py migrate"

language: "python"

python: 
  - "3.7.4"

script: "python manage.py test"

after_script: "deactivate"