--- 
before_install:
  - "cd .."
  - "python -m pip install virtualenv"
  - "virtualenv venv"
  - "source venv/bin/activate"
  - "cd boards"

install: 
  - "pip install -r requirements.txt"
  - "python manage.py migrate"

language: "python"

python: 
  - "3.7.4"

before_script: "python manage.py collectstatic --no-input"

script: "python manage.py test"

after_script: "deactivate"